services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/app/local_data
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: go_webapp
    ports:
      - "8080:8080"
    environment:
      QDRANT_API_URL: ${QDRANT_API_URL}
      MONGO_DB_URI: ${MONGO_DB_URI}


volumes:
  qdrant_data:
  mongodb_data: