services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "9000:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: vectordb
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "9001:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/backup:/app/backup_data
    environment:
      - MONGO_INITDB_DATABASE=books
    restart: unless-stopped

volumes:
  ollama_data:
  qdrant_data:
  mongodb_data: